# Generated by Django 6.0 on 2025-12-27 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceteam',
            options={'ordering': ['name'], 'verbose_name': 'Maintenance Team', 'verbose_name_plural': 'Maintenance Teams'},
        ),
        migrations.RemoveField(
            model_name='maintenanceteam',
            name='team_name',
        ),
        migrations.AddField(
            model_name='maintenanceteam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceteam',
            name='description',
            field=models.TextField(blank=True, help_text='Team specialization and responsibilities', null=True),
        ),
        migrations.AddField(
            model_name='maintenanceteam',
            name='name',
            field=models.CharField(default='Unnamed Team', help_text="Unique team name (e.g., 'Hydraulics Team', 'Electrical Team')", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='maintenanceteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenanceteam',
            name='members',
            field=models.ManyToManyField(help_text='Team members eligible to be assigned as technicians', related_name='maintenance_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
