# Generated by Django 6.0 on 2025-12-27 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('teams', '0002_alter_maintenanceteam_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='maintenance_team',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='warranty_end',
        ),
        migrations.AddField(
            model_name='equipment',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, help_text='Primary employee responsible for this equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='default_maintenance_team',
            field=models.ForeignKey(blank=True, help_text='Default team for maintenance requests on this equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_equipment', to='teams.maintenanceteam'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, help_text='Date warranty expires', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='default_technician',
            field=models.ForeignKey(blank=True, help_text='Preferred technician for this equipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_technician_for_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='department',
            field=models.CharField(help_text='Department responsible for this equipment', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_scrapped',
            field=models.BooleanField(default=False, help_text='Whether equipment is logically scrapped (not deleted from system)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(help_text="Physical location within facility (e.g., 'Building A, Floor 2, Section 3')", max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text="Equipment name (e.g., 'Hydraulic Press A1', 'CNC Machine 3')", max_length=150),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(help_text='Date equipment was purchased'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(help_text='Unique manufacturer serial number', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='equipment_e_serial__b7639f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_scrapped'], name='equipment_e_is_scra_2dd4d7_idx'),
        ),
    ]
