# Generated by Django 6.0 on 2025-12-27 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('Corrective', 'Corrective'), ('Preventive', 'Preventive')], max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Repaired', 'Repaired'), ('Scrap', 'Scrap')], default='New', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.maintenanceteam')),
            ],
        ),
    ]
