# Generated by Django 6.0 on 2025-12-27 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_remove_equipment_assigned_to_and_more'),
        ('maintenance', '0001_initial'),
        ('teams', '0002_alter_maintenanceteam_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Maintenance Request', 'verbose_name_plural': 'Maintenance Requests'},
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='team',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_team',
            field=models.ForeignKey(blank=True, help_text='Team assigned to handle this request (auto-filled from equipment default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='teams.maintenanceteam'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this maintenance request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='due_date',
            field=models.DateField(blank=True, help_text='Target completion date', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, help_text='Individual technician assigned to complete the work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='duration',
            field=models.FloatField(blank=True, help_text='Estimated or actual duration in hours', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='equipment',
            field=models.ForeignKey(help_text='Equipment requiring maintenance', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_type',
            field=models.CharField(choices=[('Corrective', 'Corrective - Emergency/Unplanned'), ('Preventive', 'Preventive - Scheduled Maintenance')], help_text='Type of maintenance request', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Scheduled date for preventive maintenance', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('New', 'New - Created, not yet assigned'), ('In Progress', 'In Progress - Technician is working'), ('Repaired', 'Repaired - Completed successfully'), ('Scrap', 'Scrap - Equipment marked for disposal')], default='New', help_text='Current status of the maintenance request', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='subject',
            field=models.CharField(help_text='Brief description of the problem or maintenance task', max_length=255),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='maintenance_status_0773c2_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['request_type'], name='maintenance_request_2ba654_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['equipment'], name='maintenance_equipme_3db785_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['assigned_technician'], name='maintenance_assigne_c31a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['scheduled_date'], name='maintenance_schedul_c5df1b_idx'),
        ),
    ]
